version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: rello-backend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: rello-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rello
    ports:
      - "5432:5432"
